Wallet persistence.
srijan-paul/BitHounds pull request #21
Opened 2021-09-22 09:39 UTC by srijan-paul

Even on reloads, we can detect an existing wallet and display the address like Pixel Potus.
![image](https://user-images.githubusercontent.com/50487716/134320344-23613e0d-0d9f-4181-be9f-82a2ed8581f9.png)

2021-09-24 04:42 UTC, Mihir018 commented on src/components/ConnectWallet.tsx
> +  if (!isConnected) {
I think a `disconnectwallet` button would be good to have if user wishes to change the address.

2021-09-26 04:45 UTC, Mihir018 commented on src/components/pages/Profile.tsx
> +          )}
I think it would be good if we also keep check of `parent1 != parent2`, but I am not sure.

2021-09-29 08:38 UTC, ahv15 commented on src/components/pages/Hound.tsx
> +          <div className="houndInfo__field">Spriti Animal: {houndInfo.stats.spiritAnimal}</div>
Spriti - Spirit

2021-09-29 12:02 UTC, Mihir018 approved these changes
I think we can improve the breeding logic to get more randomness, but for now I feel it is good to merge.

![hounds](https://user-images.githubusercontent.com/51472181/135264360-1e737fa7-52f0-4e1d-a53b-34f774c8398f.png)

2021-10-10 13:31 UTC, Mihir018 requested changes

2021-10-10 13:31 UTC, Mihir018 commented on src/components/pages/Market.tsx
> +  const mapOfHoundsOnSale: Map<string, ContractHound> = tzContext.contractStorage.market.valueMap;
![Screenshot 2021-10-10 182121](https://user-images.githubusercontent.com/51472181/136697710-a5b6acba-d2db-4020-aa9b-c9d88f0b6580.png)
await `tzContext.loadContract()` will be needed to keep check when page is refreshed.

2021-10-10 14:25 UTC, ahv15 commented on src/components/pages/Market.tsx
> +  const mapOfHoundsOnSale: Map<string, ContractHound> = tzContext.contractStorage.market.valueMap;
can we merge this and make incremental fixes in smaller and separate PR's?

2021-10-10 14:45 UTC, Mihir018 approved these changes

2021-10-10 15:44 UTC, merged